"""Shared infrastructure layer."""

# Local imports
from .cache import cache, CacheService
from .config import settings
from .database import AsyncSessionLocal, close_db, get_db_session, init_db
from .error_handlers import (
    AuthenticationError,
    AuthorizationError,
    CacheError,
    DatabaseError,
    ErrorContext,
    ErrorHandler,
    ErrorMiddleware,
    ExternalServiceError,
    RateLimitError,
    handle_errors,
    retry_on_error,
)
from .logging import get_logger, get_request_logger, log_performance, setup_logging
from .middleware import (
    CacheMiddleware,
    LoggingMiddleware,
    RateLimitMiddleware,
    SecurityMiddleware,
)
from .models import Base, DomainBase, SoftDeleteMixin, TimestampMixin
from .repositories import InMemoryRepository
from .sql_repositories import SQLRepository, SQLRepositoryWithRelations
from .validation import (
    EmailField,
    FilterCondition,
    FilterOperator,
    FilterParams,
    PaginatedResponse,
    PaginationParams,
    PasswordField,
    PhoneField,
    PositiveDecimalField,
    QueryParams,
    SearchParams,
    SortOrder,
    SortParams,
    URLField,
    UUIDField,
    format_validation_errors,
    sanitize_input,
    validate_email,
    validate_file_extension,
    validate_file_size,
    validate_password_strength,
    validate_phone,
    validate_positive_decimal,
    validate_uuid,
    validate_url,
    validate_input,
)
from .service_client import ServiceClient, ServiceRegistry, service_registry, call_service, call_service_with_retry
from .monitoring import (
    metrics_endpoint,
    update_health_status,
    update_database_connections,
    update_redis_connections,
    update_cache_hit_ratio,
    track_request_metrics,
    track_business_metrics,
    track_performance,
    MetricsMiddleware,
    http_requests_total,
    http_request_duration_seconds,
    orders_created_total,
    products_viewed_total,
    users_registered_total,
    reviews_created_total,
    errors_total,
    health_check_status,
)

__all__ = [
    "settings",
    "cache",
    "CacheService",
    "setup_logging",
    "get_logger",
    "get_request_logger",
    "log_performance",
    "LoggingMiddleware",
    "CacheMiddleware",
    "RateLimitMiddleware",
    "SecurityMiddleware",
    "ErrorHandler",
    "ErrorMiddleware",
    "ErrorContext",
    "AuthenticationError",
    "AuthorizationError",
    "RateLimitError",
    "DatabaseError",
    "CacheError",
    "ExternalServiceError",
    "handle_errors",
    "retry_on_error",
    "EmailField",
    "PasswordField",
    "PhoneField",
    "UUIDField",
    "PositiveDecimalField",
    "URLField",
    "PaginationParams",
    "PaginatedResponse",
    "SortOrder",
    "SortParams",
    "FilterOperator",
    "FilterCondition",
    "FilterParams",
    "SearchParams",
    "QueryParams",
    "validate_email",
    "validate_password_strength",
    "validate_phone",
    "validate_positive_decimal",
    "validate_uuid",
    "validate_url",
    "sanitize_input",
    "validate_file_extension",
    "validate_file_size",
    "format_validation_errors",
    "validate_input",
    "get_db_session",
    "AsyncSessionLocal",
    "init_db",
    "close_db",
    "Base",
    "DomainBase",
    "TimestampMixin",
    "SoftDeleteMixin",
    "InMemoryRepository",
    "SQLRepository",
    "SQLRepositoryWithRelations",
    "ServiceClient",
    "ServiceRegistry",
    "service_registry",
    "call_service",
    "call_service_with_retry",
    "metrics_endpoint",
    "update_health_status",
    "update_database_connections",
    "update_redis_connections",
    "update_cache_hit_ratio",
    "track_request_metrics",
    "track_business_metrics",
    "track_performance",
    "MetricsMiddleware",
    "http_requests_total",
    "http_request_duration_seconds",
    "orders_created_total",
    "products_viewed_total",
    "users_registered_total",
    "reviews_created_total",
    "errors_total",
    "health_check_status",
]
